var width = 2;
var height = 3;
var area = width * height;
console.log('value of area:', area);
console.log('typeof area:', typeof area);
var bill = 8;
var payment = 10;
var change = payment - bill;
console.log('value of change:', change);
console.log('typeof change:', typeof change);
var quizzes = 90;
var midterm = 90;
var final = 90;
var grade = (quizzes + midterm + final) / 3;
console.log('value of grade:', grade);
console.log('typeof grade:', typeof grade);
var firstName = 'Kyle';
var lastName = 'Kriske';
var fullName = firstName + ' ' + lastName;
console.log('value of fullName:', fullName);
console.log('typeof fullName:', typeof fullName);
var pH = 4;
var isAcidic = pH < 7;
console.log('value of acidic:', isAcidic);
console.log('typeof isacidic:', typeof isAcidic);
var headCount = 10;
var isSparta = headCount === 300;
console.log('value of isSparta:', isSparta);
console.log('typof isSparta:', typeof isSparta);
var motto = fullName + ' is the GOAT';
console.log('value of motto:', motto);
console.log('typeof motto:', typeof motto);
